name: HabSat - Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Integration Tests
    uses: grupacosmo/habsat-starter/.github/workflows/integration-tests.yaml@master

  build:
    name: Build
    needs: [tests]
    uses: grupacosmo/habsat-starter/.github/workflows/build.yaml@master
    with:
      DOCKER_HUB_REPOSITORY: cosmopk/habsat-post-service
      DOCKER_HUB_TAGS: master
    secrets: inherit

  deploy-staging:
    name: Staging
    needs: [build]
    uses: grupacosmo/habsat-starter/.github/workflows/deploy.yaml@master

  e2e-tests:
    name: E2E Tests
    needs: [deploy-staging]
    uses: grupacosmo/habsat-starter/.github/workflows/e2e-tests.yaml@master
